APP_URL: ENC[AES256_GCM,data:NBNJJTuVL3ZvZ0LHHLnX,iv:IxutQkzypGK+fEAqSwIweQ9mRYt5VBOCh0fcxUVL/EU=,tag:YrP4AlAacLUsbw7H0BVp9Q==,type:str]
CODE_REPO: ENC[AES256_GCM,data:/oKXHCHuQnNEV+QyEiE=,iv:qUdyVUA3QLJ2L5jT+H5MgvV9hkE5VacemLXSrcy9pAg=,tag:g4Df8gvrogzKEmYRvLgq9w==,type:str]
PROJECT_DIR: ENC[AES256_GCM,data:oSfoXwv2veCnpm2vZ6t3JNsdVBYV1rV9XZjV2w==,iv:V6GZHobtIp2LpoCugvOwHho+EssuKGnUqg4PhGhcLkE=,tag:zSG/TIYDv9EoYcPGRUXehA==,type:str]
WEB_PORT: ENC[AES256_GCM,data:RcrFMw==,iv:8oo60M21mbnsIEgbcXBhty5hw5rwC20ea62eTaVls84=,tag:vleB3r26jxgAax26X82VoQ==,type:str]
APP_PORT: ENC[AES256_GCM,data:JrszE3Hkl+LDvaZnQ5w=,iv:TmkkDS2ptnMSVsPIiYAn/zyqqI7zWqCFvkQ/ihI5tng=,tag:7WNtpBOotya63ZO4SUP2KA==,type:str]
WEB_SERVER_USER: ENC[AES256_GCM,data:sctDyfIzRsM=,iv:TZaXSkbfd6JHpkD1XrbYd/SBm92iLBEXDKT5WZuE+08=,tag:g0a0swIkzQGsirD2t5ktKQ==,type:str]
DOCKER_USERNAME: null
DOCKER_PASSWORD: null
DOCKER_EMAIL: ENC[AES256_GCM,data:G0UvltTpYonq7IbyN0OYy9CQiw==,iv:hdrj+PJ+OxElcqDwn2fDS9WLsRJ089iqkogElZOX2nQ=,tag:uCW5//wVyC6quj/ZiO04DQ==,type:str]
DOCKER_REPO: ENC[AES256_GCM,data:+IN5RVfGCx2ZKOLsXOcG2LXNhw==,iv:dBDBWq1N0T6RuwWHdagULaKVQVbxfC11x/yPKJuMK/8=,tag:JKNdw9yZlVUkE+Zfg9IJAw==,type:str]
DOCKER_PORTS:
    - ENC[AES256_GCM,data:tpEujFeC68VxDEsjwCxpU/jr/ylFbbMwyPLJp+xqfsxzBuAfI0nA,iv:Tl6ulF/UcObPq42CcCoj7c873dOzUkktuA5EN0IA+JM=,tag:S0RTuaTk8GL7v2LzQiUIzg==,type:str]
DOCKER_ENV:
    NEXT_PUBLIC_EXCHANGE_RATE_API_URL: ENC[AES256_GCM,data:I/ZInXOk7NixA91yXMa1DZ+ELT6h08cnFq+bVd9tJmumj0A=,iv:2NpnjqdPn9hbh2jAufKqthaOm6R0xH2iucP6siGe4JQ=,tag:o/5j1aSlq8/ozeYR5DbrTA==,type:str]
    NEXT_PUBLIC_TRANSLATION_API_URL: ENC[AES256_GCM,data:LSWlCAqq9mLJ7fR/EltocN9ffAmTqreu141OyUW9Uv1r/QY=,iv:fj8JImI1sIhfOqSstObK3IRt16RuUdT2X2OdgMRXIo4=,tag:/ZvF47g9IUEsSJUQX7t+AA==,type:str]
    NEXT_PUBLIC_IMAGE_PROCESSING_API_URL: ENC[AES256_GCM,data:8JsGxYEgIE2Fp9Bh5wXIQ/5YmwnQ2pm4DxDwoDs=,iv:N4t0PMUJqtNmGtkkpJ0+a6xOssGJAxFvt2c7QVuXV68=,tag:6iop7QNJejBN9qG7Yu1DYA==,type:str]
    NEXT_PUBLIC_BARCODE_API_URL: ENC[AES256_GCM,data:ZR532XAM04+1GOzhjq1P9EO+WtAiWutyv+tj0iBuZw==,iv:R/Chmt1yBo3nfKuonFHGgp6zAcEmSykjUL4dyU74R/c=,tag:pW9E53FYzey3xx+hnOba9A==,type:str]
    NEXT_PUBLIC_PDF_API_URL: ENC[AES256_GCM,data:WWmQKMCRUmDWB3tzhejgRGWObKdhl9tT8KrK,iv:y05iGVuZNYEznih4HfqatAQ/Pp8yv/DQkdObg5pUWt4=,tag:V76iCWGK8QMsbF6t1vazfA==,type:str]
    NEXT_PUBLIC_TAG_MANAGER_KEY: ENC[AES256_GCM,data:je2y4GOKS5vnjyVw,iv:aJ/sI7vDudHZDpMbZc1MGfTTdh9XYp7c8souBBC6ghk=,tag:W2h98iAhM/fB7FHGYzwSGw==,type:str]
    NEXT_PUBLIC_SENTRY_AUTH_TOKEN: ENC[AES256_GCM,data:50YEnFCU32Qn/IqpgPyNpskCA6IS0ufY6YHpih0Jr92KfyCW5hZelMsvG1UUnYClwvCjNyMZkcX1HFWuYxXH4b7ARqbBc76sityBtrrnQtU13uh38RwuJXn1CX8g1b5FCGWsULnASSvWDsTUlqX+Q/eeFg0NKlsLtkYR8xS8SCA4zS5hgJ38wMB/EXq5bW9qf2Ro3REbwr+5qdNmYnDXiDfyKLE7AGsDv1o5qnbUeM6PqN7FUsWHyaaFFz1RIdQ=,iv:WNaf6RuvYNUaQuMGSTcqz/XGFkOkCYHLmQ7p4R3dMO4=,tag:K3ywLXHKBiVyW66aD4e4gA==,type:str]
    NEXT_PUBLIC_SENTRY_ORG: ENC[AES256_GCM,data:vDDJV0Pyrpbl,iv:EE3aZEoMPZkx7AMbucVj+wbNrmr5Ucg1AyEvufBljos=,tag:QbyjzgUf29ukjcc/BOgVaQ==,type:str]
    NEXT_PUBLIC_SENTRY_PROJECT: ENC[AES256_GCM,data:yKP/6FQKDftF,iv:vpAS9UrleY7Pm0sopg7gIHxl8fAY8xWN7FuT4hRPSM4=,tag:538gT5iSpDdP4USmiL4lww==,type:str]
    NEXT_PUBLIC_POSTHOG_KEY: ENC[AES256_GCM,data:12jD0zF8OxP9vBFHvu6t2sSLzixGL9ms56BG4XIRmhx1/8zsgRUgL8anTSupxV4=,iv:VGitaDfhZw8YgZIjeBoaE0ukLz462bBg5bHnuVIhzMo=,tag:nQvKDx+x+K35TmYoLxS+9Q==,type:str]
    NEXT_PUBLIC_POSTHOG_HOST: ENC[AES256_GCM,data:JLPqDzZGuhzZ0LH6/cm/VSVSPpTTUbkY,iv:2anZeHk7RcSwnfcfjY72w+c/b6/BVhMq7vuVIYnBTUM=,tag:krAXtGbVzst3niD++9FEcA==,type:str]
force_config: ENC[AES256_GCM,data:MTPtxw==,iv:XbNIAr6xYqI1FbypfVNJ4Qbbn986uX91oV3w7tow07c=,tag:6T1DiUtHgd48FsN3oKw05g==,type:bool]
LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:nLRhi1aMAj0D1SppFHTuxj1frUnWLw==,iv:X+JiaRP5capE88pWnjE1naLDCMQL/lll92r96dF7lPE=,tag:voLSoKupQmi7Dc6HvBSXVg==,type:str]
LETSENCRYPT_DIR: ENC[AES256_GCM,data:xC7V7mKHf7ub7L2mI90UuC4wbqfb,iv:Q+seaJVZFYRKVfnMl/QvPGlrhSMwkVrQnmFTl8wDQVY=,tag:Qh+isr2huMmCoPi/AP60Sw==,type:str]
certbot_create_if_missing: ENC[AES256_GCM,data:W56Qrg==,iv:Z28irIVlAKMY2os8o6IJNIyDEpHcmCkBEZAc8KAaq2c=,tag:Hx8qe8lDwFMwnoAJE8aqoA==,type:bool]
certbot_dir: ENC[AES256_GCM,data:broC35GXXFisCWWT1+YVtk6IxsK4,iv:TxtAjfyNtv/enTV1/2HnAH0ahJIY798X5wfQ0dnhktc=,tag:7SdZBkbEK36SQ3DI0rGHQQ==,type:str]
certbot_create_standalone_stop_services:
    - ENC[AES256_GCM,data:w85LJBw=,iv:vglIEE/vE0/2q9bEDDN66Vhtbd5HiwMo/9LOuBmfR3E=,tag:tesPRO8lTTTIpT1XbFYCAg==,type:str]
certbot_certs:
    - email: ENC[AES256_GCM,data:ajfVKBQxZmIHZ/VNoG+IHTIbV+bSrEM=,iv:e39a32Jy268ItjQBJjReOSC64z16B4n6q02+NKg3UzM=,tag:Ql8yhxjTnHPBNpZGutjpfw==,type:str]
      domains: ENC[AES256_GCM,data:+RD18T6YT0DqkvzoAA==,iv:Ebt7mVBO58qZ7Vg5T7rjtnM+Wx00iqXQ1Q/ELo60q08=,tag:ZQNqdOxoQ9n7X3wpjJP/0A==,type:str]
certbot_keep_updated: ENC[AES256_GCM,data:MZqp,iv:jsnVjhMo/jbjv034I9XWR0bjXArjqp77O0wLc0A6fiM=,tag:vU/NcrNaW+vQbdQZp+9Ysw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:143188609111:key/8fc6f01a-3289-4fb4-b9e7-cab31c54a4ea
          created_at: "2025-03-21T07:16:46Z"
          enc: AQICAHgxToX4Pp90hvfJQ4E9+h6aXlRo2IWXaPLiRXBaMnIbJwGvQ8p84iLNG6bl6q4xTPkqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0HGAtswHFWcPJiNVAgEQgDuzWHtRsjkL0BKfI6h0e2D5AdAitdWFjg/d8g04fXe24fg54YfOAuXRh7l7PG+sBqruMwtTXI3RB449Ww==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-21T07:16:46Z"
    mac: ENC[AES256_GCM,data:qHEQtws06ExPS9ZPlFVo4+4YgtczucVMcJdM7HkYRRX2RuEIJBK6AWWBfX0vZ9RWmlhmMp/M5KVO+f55fChgApo2a8OyKfSp9HpaxxWJdNPOzXw3a44MVlxXkxmsN51BdB1uqQw7jx3gAjijEKhcs6qIrujXQj1HOOCCsEUh63c=,iv:LicyrpPGo3zjZiFnXBxfF4Nqv10IJMBaB8DrEpK4Ar0=,tag:P0t8nQUZYoEMS2En48JjGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
