APP_URL: ENC[AES256_GCM,data:1lOuchVEDuuNu3l/YKO23Jc4F6Sp1A==,iv:m+1VOpm+DviGo4VietAbbusHQpVij0YcJuCzhImXc+Y=,tag:38V8v1iUzyuXnm0AaFI4Gw==,type:str]
CODE_REPO: ENC[AES256_GCM,data:O1rk+HRzkNu7eWEB+EU=,iv:+ch0r+bEIIwusBPlEUdU+ja0yosKHiJ/wVsbxFgZ12w=,tag:+uBz/4IExJy5r7Vft097uA==,type:str]
PROJECT_DIR: ENC[AES256_GCM,data:QcsDQQ3MjEuNKKjqXYAypp/cx7klH9ktSdb9zw==,iv:DlVKmtYyWJFlakFds1TpkVm3X0MnSNZZVYSB5acdkDQ=,tag:50pJlqFAc1zMnUhXTf05gQ==,type:str]
WEB_PORT: ENC[AES256_GCM,data:/JbqWw==,iv:+muXlEO9OICDHnuyttNaJessrXdpqUxI90ynR8fyLWg=,tag:qwU77e7lwdCh/2nQNiwBrg==,type:str]
APP_PORT: ENC[AES256_GCM,data:Acn5Jb98GMMas5lfiEQ=,iv:X95+8Q3HPhu/lN9nFCW/NvE/jH0cZaSt2uHIBhQ+qA4=,tag:8tR69oGD5xTWjabUc69ksQ==,type:str]
WEB_SERVER_USER: ENC[AES256_GCM,data:FVRj01jgSn0=,iv:0HMeOq5xsav/z6kBNsCFefGPm7bT2Rq8l/9es1Lda78=,tag:7ISiyORLn2VSL3NCudqbJQ==,type:str]
DOCKER_USERNAME: null
DOCKER_PASSWORD: null
DOCKER_EMAIL: ENC[AES256_GCM,data:zR3FnWRNqn+EFqjfMl2qXNXt2A==,iv:Yqa7Yj9L/A+drSgFzKV0T7wRmIMwEDq+HZ5zdat1m40=,tag:MdT8rOBEf/h+lnneYFMqhA==,type:str]
DOCKER_REPO: ENC[AES256_GCM,data:2ZN/dgrGWXIAbYRx2rjPNZOj6Q==,iv:/r+XXAgsQvowf+GkVgMl4ek2oPuKs0Gz6PCVDX3/nQU=,tag:TETZkMrNGbX+22xrqMVZAg==,type:str]
DOCKER_PORTS:
    - ENC[AES256_GCM,data:Z2wRAHA0hgjuyzwO2NulW1PEfKOuH7eTZdKxqyx9VO438xStBi9K,iv:UFuYSBCvJKJ4bAn00UIpRHP9q8/ZhIjv5+i+m/2vpMw=,tag:2iMmNDJfKOhJvibwHvVAVA==,type:str]
DOCKER_ENV:
    NEXT_PUBLIC_EXCHANGE_RATE_API_URL: ENC[AES256_GCM,data:ft+Caj8p8JOsn5alqnLQh6m6LalNdDJkpKjghL1kpM70CfU=,iv:WZmn/fk+KO0CEkLOAF+Gs7MSMhjgMnj1QHLdczAzHOU=,tag:v01tss41ggvJBzSFYZnMyA==,type:str]
    NEXT_PUBLIC_TRANSLATION_API_URL: ENC[AES256_GCM,data:UZIvMGxP3rbm5TxT9d7plcdOZDLLMip8DGYLOw/zsu75BUQ=,iv:/NHy/TNwCDOl5br6GqTBvCSO14oLySZqb99LcGcE0P8=,tag:SbfGFf2jYiS9kK24EEY4Mg==,type:str]
    NEXT_PUBLIC_IMAGE_PROCESSING_API_URL: ENC[AES256_GCM,data:oo/rloWO3mmpDBWKACRo2tlxqWMU2YakFOGA4qQ=,iv:VEl40R0v0TIRklD4GK//fRPCEFfQPdg8Jxhh9je9GwE=,tag:N+o6xLRmNbRYtClucwk9KQ==,type:str]
    NEXT_PUBLIC_BARCODE_API_URL: ENC[AES256_GCM,data:GWd7wpCwz9G6i3f/z7ExA947P6drwjtOyFyjqJqMkQ==,iv:s8GryF17Oo9THs58114mc97ie0PWQLVb5aMnwX0BlpI=,tag:Kcvw0YpLwhNKsrAQPN8ldg==,type:str]
    NEXT_PUBLIC_PDF_API_URL: ENC[AES256_GCM,data:8Jtd9Aq7a2X1LmpfVl/vGpTEKM8Z+DOcUWAE,iv:LSMwL+ZjWH6AM+9T4yMxgyflGqVOcI4/xGwA/9M3b7Y=,tag:F/xfTBDsDBhj28OpgkSN+w==,type:str]
    NEXT_PUBLIC_TAG_MANAGER_KEY: ENC[AES256_GCM,data:pDHFHZcG304HAIER,iv:3bnzob3bIw3Jr5y6hWhIdkmpE3v6Vwuu5+PI3Zj1uv0=,tag:TilzOLOxb9z7ESgaitkCzw==,type:str]
    NEXT_PUBLIC_SENTRY_AUTH_TOKEN: ENC[AES256_GCM,data:pVb9xJ/RSn3+ibuEWh81F/F3dW/z6hXF4ihbiZHgUMVtTvlgokzLVcHz+3kS9HpOWGuBlcJAfiuN72A6fF3vThTB+iM8V9w+GyezaUjJOUbpjwQ0PkW9PxkR42CScf4adytvw975QozNkavRG92T59aVYXowPAUYPys9omvhZm6kh+TZ6a37wk8lHbxYPOzdNwidqDu6p51CUgGrN0sG9U+PHTX+S62F0e5fOg7juSoW3gNnagIjWrdeSWCwp+M=,iv:yCwhZZKEvkbD9/bky8t6Gi2qOT9SqFSEyxWEnf2v7cI=,tag:z+lmCNNFu3Z7ScnUV7/6iw==,type:str]
    NEXT_PUBLIC_SENTRY_ORG: ENC[AES256_GCM,data:+VatfMoyLYuZ,iv:XQYADXxUdWp56JCTwAMzvSiOebOL7xV+8qeY53RTryc=,tag:afxHff7k3T041h9DAmh7LQ==,type:str]
    NEXT_PUBLIC_SENTRY_PROJECT: ENC[AES256_GCM,data:s+YemPS7uDam,iv:8/YkRr78OkmB4t9sg9HpSwqbOm7DHkPpLPcWByK14I0=,tag:KXAr3PX32J9vCg+eKtnl5w==,type:str]
    NEXT_PUBLIC_POSTHOG_KEY: ENC[AES256_GCM,data:oE/mMqdUEa0Ms53WeiriLnrxQjMVX9X5gnZNEKsAlYeqQvKWtRvcQXwHOLOkiYI=,iv:TpVM0g7wyrwfTGvvLB8lLmkKrdAMSr24n9ObK5hWIGA=,tag:8nesbsvrxenqBj6TIr/P/Q==,type:str]
    NEXT_PUBLIC_POSTHOG_HOST: ENC[AES256_GCM,data:0IVXqvx9v3fir0ZRTLCgGx+kG36GPpQG,iv:WybePWNasSkjwl+MjZYWOvoO3fpD2P5PVMQeTpMq4PE=,tag:QpSSeVWkh+mjR+lVvuFwOA==,type:str]
force_config: ENC[AES256_GCM,data:4W9izQ==,iv:IJyCvMocHa0jlqyamf+DuQm8+v3RJHO0xV2YxghOGvY=,tag:U/KoZB44m1KZbiS5XMSjug==,type:bool]
LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:ONH0Gnzp8UhzA2T0aIEECyFmFkJUWQ==,iv:dmUAa5FRAjD1QUEx8xV1uVjD3LYgvRUEgbmnaJLbnUI=,tag:iVDYCXzW2zAamqJIc690gw==,type:str]
LETSENCRYPT_DIR: ENC[AES256_GCM,data:bnTpJrfJImXvLjjTjey32mNTIXgv,iv:k3X3eGXfHpQicfKY1jrak3bQeSAO+4n6Dq2yj0j6ARs=,tag:Gf0k3MQcpEXobmcGc+WsMg==,type:str]
certbot_create_if_missing: ENC[AES256_GCM,data:QLAzbw==,iv:lIODlUvbX+HaQhNoo+Q3DsbCH0hEvWo6lkiPJxTYfrc=,tag:K0i8rHb9NnsqtXC2nYRYmQ==,type:bool]
certbot_dir: ENC[AES256_GCM,data:GdEEaDs5GqW6vyW+LCVh38HUqwx1,iv:D2ND6FNWDy6KPC2DJ7pVQmIyXFAL31yX3nqiHGZv9Xs=,tag:D6BUBNQ+3HQF4IEKDfpaWQ==,type:str]
certbot_create_standalone_stop_services:
    - ENC[AES256_GCM,data:anRSyaQ=,iv:vUSdkOpBXZh2eLTofxx7Ne/7GFF1rGzJZkU76ib09a8=,tag:4OeiqzwQav4fROMGSofu/A==,type:str]
certbot_certs:
    - email: ENC[AES256_GCM,data:ik3BW1trpCoxUJv9g/5wz2RpC87BlrQ=,iv:3DT/NTilNj3aHRvAyZolda9YxU0voTTadDVsPSuye2I=,tag:IDIBYPnL5WpaagL1tfyCPw==,type:str]
      domains: ENC[AES256_GCM,data:OaR7Id7x/lklFs9B2A==,iv:XtCYzlcm4Gv+dG6ujIGNCOs8p4/7fSrdMf1E8IV3RYU=,tag:VRyijBVBAgh6GMgc63a9kQ==,type:str]
certbot_keep_updated: ENC[AES256_GCM,data:Erqr,iv:GqmfQYIqHaCUvNYkh0t43WQpPXDPy8tbzg8lIFmoOik=,tag:BYFJuir9iLsvk2O5hBVEcQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:143188609111:key/8fc6f01a-3289-4fb4-b9e7-cab31c54a4ea
          created_at: "2025-03-21T07:16:45Z"
          enc: AQICAHgxToX4Pp90hvfJQ4E9+h6aXlRo2IWXaPLiRXBaMnIbJwFpkRThlSGScPP2/o8H7wo2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQ5b7XSyAfoRzAiB3AgEQgDsDmlWxL7o46UlCj+WcCDiDqJuXr1OfOv1+I2UeYXXIiM9KA69ju4rvej6Sn6N6OelR6RNDaKTITKcFgw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-21T07:16:45Z"
    mac: ENC[AES256_GCM,data:i+r632JM3UehfbdNuDR0IJSkxKRuUlYruXo4w9VcSca4r2KX28NrHOkxvkkk5A4wHQdwXhkTZniK8zdf8w6RLYBC4Lo9hEs05ukODIGdfPethkbsVoAjayCSjiHrKvb0ezMCLAtmP2yIThxQRHyFyEN7rCN6MrNuIW31wYeEI7I=,iv:nzsFqjRlL9Ks/c/c6oDKRu6gD52UxP9vnitNToZfdhY=,tag:G4cqerDPS3DGJCu2Yt82+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
